const jobPositionsMockArray = [
  "Professional Procrastinator",
  "Chief Coffee Drinker",
  "Senior Social Media Scroller",
  "Director of Doodling",
  "Executive Napper",
  "Head of Office Gossip",
  "Chief Distraction Officer",
  "Director of Online Shopping",
  "Vice President of Water Cooler Chats",
  "Chief YouTube Watcher",
  "Senior Snack Taste Tester",
  "Director of Meme Creation",
  "Head of Instagram Filters",
  "Chief Emoji Communicator",
  "Vice President of Desk Decorations",
  "Master of Conference Calls",
  "Chief Cat Video Viewer",
  "Director of Emoji Interpretation",
  "Vice President of LinkedIn Endorsements",
  "Senior Sarcasm Specialist",
  "Executive Email Checker",
  "Chief Meeting Scheduler",
  "Director of Paper Clip Bending",
  "Vice President of Procrastination Strategies",
  "Head of Keyboard Shortcuts",
  "Chief Desk Toy Organizer",
  "Senior Internet Surfer",
  "Director of Online Cart Filling",
  "Executive Nap Planner",
  "Chief Social Media Hashtag Creator",
  "Vice President of Netflix Recommendations",
  "Senior Email Forwarder",
  "Director of Pen Clicking",
  "Head of Funny Video Sharing",
  "Chief Internet Researcher",
  "Executive Snack Organizer",
  "Vice President of Lunch Planning",
  "Senior Pencil Sharpener",
  "Director of Office Chair Racing",
  "Head of Post-It Note Design",
  "Chief Paper Clip Straightener",
  "Executive Staple Remover",
  "Vice President of Break Room Etiquette",
  "Senior Office Supply Hoarder",
  "Director of Desk Drawer Organization",
  "Head of Coffee Stain Removal",
  "Chief Sarcasm Translator",
  "Executive Keyboard Cleaner",
  "Vice President of Office Pranks",
  "Senior Mouse Pad Designer"
];

export default jobPositionsMockArray;